/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionarchivos;
import java.io.File;
import javax.swing.*;
/**
 *
 * @author luisenrique
 */
public class JFGestionA extends javax.swing.JFrame {
JFileChooser seleccionado=new JFileChooser();
File archivo;
byte[]bytesImg;
GestionA gestion=new GestionA();


    /**
     * Creates new form JFGestionA
     */
    public JFGestionA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAbrirArchivo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblImagen = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtAreaTexto = new javax.swing.JTextArea();
        btnGuardarImagen = new javax.swing.JButton();
        btnGuardarTexto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GESTION DE ARCHIVOS IMG Y TXT");

        btnAbrirArchivo.setText("ABRIR ARCHIVOS");
        btnAbrirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirArchivoActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lblImagen);

        TxtAreaTexto.setColumns(20);
        TxtAreaTexto.setRows(5);
        jScrollPane2.setViewportView(TxtAreaTexto);

        btnGuardarImagen.setText("GUARDAR IMAGEN");
        btnGuardarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarImagenActionPerformed(evt);
            }
        });

        btnGuardarTexto.setText("GUARDAR TEXTO");
        btnGuardarTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarTextoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(btnAbrirArchivo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(btnGuardarImagen)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardarTexto)))
                .addContainerGap(1439, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAbrirArchivo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarImagen)
                    .addComponent(btnGuardarTexto))
                .addContainerGap(246, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbrirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirArchivoActionPerformed
        if(seleccionado.showDialog(this,"ABRIR ARCHIVO")==JFileChooser.APPROVE_OPTION){
            archivo=seleccionado.getSelectedFile();
            if(archivo.canRead()){
                if(archivo.getName().endsWith("txt")){
                    String contenido=gestion.AbrirATexto(archivo);
                    TxtAreaTexto.setText(contenido);
                }else{
                    if(archivo.getName().endsWith("jpg")||archivo.getName().endsWith("png")||archivo.getName().endsWith("gif")){
                        bytesImg=gestion.AbrirAImagen(archivo);
                        lblImagen.setIcon(new ImageIcon(bytesImg));
                    }else{
                        JOptionPane.showMessageDialog(null,"Por favor seleccione un archivo de texto o de imagen");
                    }
                }
            }
            
        }
    }//GEN-LAST:event_btnAbrirArchivoActionPerformed

    private void btnGuardarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarImagenActionPerformed
        if(seleccionado.showDialog(this,"GUARDAR IMAGEN")==JFileChooser.APPROVE_OPTION){
            archivo=seleccionado.getSelectedFile();
            if(archivo.getName().endsWith("jpg")||archivo.getName().endsWith("png")||archivo.getName().endsWith("gif")){
                
                String respuesta=gestion.GuardarAImagen(archivo, bytesImg);
                if(respuesta!=null){
                    JOptionPane.showMessageDialog(null,respuesta);
                }else{
                     JOptionPane.showMessageDialog(null,"Error al guardar imagen");
                }
            }else{
                 JOptionPane.showMessageDialog(null,"La imagen se debe guardar en formato de imagen");
            }
        }
    }//GEN-LAST:event_btnGuardarImagenActionPerformed

    private void btnGuardarTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarTextoActionPerformed
         if(seleccionado.showDialog(this,"GUARDAR TEXTO")==JFileChooser.APPROVE_OPTION){
            archivo=seleccionado.getSelectedFile();
            if(archivo.getName().endsWith("txt")){
                String contenido=TxtAreaTexto.getText();
                String respuesta=gestion.GuardarATexto(archivo, contenido);
                if(respuesta!=null){
                    JOptionPane.showMessageDialog(null,respuesta);
                }else{
                     JOptionPane.showMessageDialog(null,"Error al guardar texto");
                }
            }else{
                 JOptionPane.showMessageDialog(null,"El texto se debe guardar en un formato de texto");
            }
    }            
    }//GEN-LAST:event_btnGuardarTextoActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFGestionA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFGestionA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFGestionA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFGestionA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFGestionA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TxtAreaTexto;
    private javax.swing.JButton btnAbrirArchivo;
    private javax.swing.JButton btnGuardarImagen;
    private javax.swing.JButton btnGuardarTexto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblImagen;
    // End of variables declaration//GEN-END:variables
}
